data:
  raw_data:
    business: "../data/raw_data/business.csv"
    economy: "../data/raw_data/economy.csv"
    full: "../data/raw_data/full_data.csv"
  clean_data:
    full_clean: "../data/clean_data/full_clean.csv"
    business_clean: "../data/clean_data/business_clean.csv"
    economy_clean: "../data/clean_data/economy_clean.csv"
  sql:
    flight: "../data/sql/flight.csv"
    itinerary: "../data/sql/itinerary.csv"
    ticket: "../data/sql/ticket.csv"
    schedules: "../data/sql/schedules.csv"
    origin: "../data/sql/origin.csv"
    destination: "../data/sql/destination.csv"
    airline: "../data/sql/airline.csv"
    number: "../data/sql/number.csv"
    class: "../data/sql/class.csv"
    stops: "../data/sql/stops.csv"